[connections.snowpark]
account = "nfjoqry-rv91310"
user = "amir"
password = "ZT&jM490!"
role = "ACCOUNTADMIN"
warehouse = "CA_TEST"
database = "CA_DATA"
schema = "INDICATORS"
client_session_keep_alive = true
